/**
 * HTML Exporter with Audio Playback
 * Creates standalone HTML files with TTS audio controls for conversations
 */

/**
 * Exports conversation to HTML with audio playback controls
 * @param {Object} conversation - Conversation object
 * @param {Object} options - Export options
 * @returns {string} HTML content
 */
function exportToHTML(conversation, options = {}) {
  const {
    includeMetadata = true,
    theme = 'light',
    autoPlay = false,
    showControls = true
  } = options;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHTML(conversation.title)}</title>
  <style>
${generateCSS(theme)}
  </style>
</head>
<body class="theme-${theme}">
  <div class="container">
    <header class="header">
      <h1 class="title">${escapeHTML(conversation.title)}</h1>
      ${includeMetadata ? generateMetadataHTML(conversation) : ''}
    </header>

    <main class="conversation">
      ${generateExchangesHTML(conversation, showControls)}
    </main>

    ${showControls ? generateControlPanelHTML() : ''}

    <footer class="footer">
      <p>Generated by Conversation Audio Processor</p>
      <p class="timestamp">Exported: ${new Date().toLocaleString()}</p>
    </footer>
  </div>

  <script>
${generateJavaScript(conversation, autoPlay)}
  </script>
</body>
</html>`;

  return html;
}

/**
 * Generate CSS styles
 */
function generateCSS(theme) {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    :root {
      --bg-primary: ${theme === 'dark' ? '#1a202c' : '#ffffff'};
      --bg-secondary: ${theme === 'dark' ? '#2d3748' : '#f7fafc'};
      --text-primary: ${theme === 'dark' ? '#f7fafc' : '#2d3748'};
      --text-secondary: ${theme === 'dark' ? '#cbd5e0' : '#4a5568'};
      --border-color: ${theme === 'dark' ? '#4a5568' : '#e2e8f0'};
      --user-bg: ${theme === 'dark' ? '#2c5282' : '#e6f7ff'};
      --assistant-bg: ${theme === 'dark' ? '#2d3748' : '#f0f4f8'};
      --accent: #667eea;
      --accent-hover: #764ba2;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      background: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.6;
    }

    .container {
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
    }

    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 30px;
      border-bottom: 2px solid var(--border-color);
    }

    .title {
      font-size: 2.5em;
      margin-bottom: 15px;
      background: linear-gradient(135deg, var(--accent), var(--accent-hover));
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }

    .metadata {
      display: flex;
      justify-content: center;
      gap: 30px;
      flex-wrap: wrap;
      margin-top: 20px;
    }

    .metadata-item {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .metadata-label {
      font-size: 0.85em;
      color: var(--text-secondary);
      margin-bottom: 5px;
    }

    .metadata-value {
      font-weight: 600;
      font-size: 1.1em;
    }

    .conversation {
      margin-bottom: 40px;
    }

    .exchange {
      margin: 30px 0;
      padding: 25px;
      border-radius: 12px;
      border: 1px solid var(--border-color);
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .exchange:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    .exchange.user {
      background: var(--user-bg);
    }

    .exchange.assistant {
      background: var(--assistant-bg);
    }

    .exchange.playing {
      box-shadow: 0 0 0 3px var(--accent);
    }

    .exchange-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 15px;
    }

    .speaker {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .speaker-name {
      font-weight: 700;
      font-size: 1.1em;
    }

    .speaker-badge {
      font-size: 0.75em;
      padding: 3px 8px;
      border-radius: 4px;
      background: var(--accent);
      color: white;
    }

    .exchange-controls {
      display: flex;
      gap: 10px;
    }

    .play-btn {
      padding: 8px 16px;
      border: none;
      border-radius: 6px;
      background: var(--accent);
      color: white;
      cursor: pointer;
      font-size: 0.9em;
      display: flex;
      align-items: center;
      gap: 6px;
      transition: background 0.2s ease;
    }

    .play-btn:hover {
      background: var(--accent-hover);
    }

    .play-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .text {
      font-size: 1.05em;
      line-height: 1.8;
      white-space: pre-wrap;
    }

    .control-panel {
      position: sticky;
      bottom: 20px;
      background: var(--bg-secondary);
      border: 1px solid var(--border-color);
      border-radius: 12px;
      padding: 20px;
      margin: 30px 0;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    }

    .control-panel-header {
      font-weight: 600;
      margin-bottom: 15px;
      text-align: center;
    }

    .control-buttons {
      display: flex;
      gap: 10px;
      justify-content: center;
      flex-wrap: wrap;
    }

    .control-btn {
      padding: 10px 20px;
      border: none;
      border-radius: 8px;
      background: var(--accent);
      color: white;
      cursor: pointer;
      font-weight: 500;
      transition: background 0.2s ease;
    }

    .control-btn:hover {
      background: var(--accent-hover);
    }

    .control-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .footer {
      text-align: center;
      margin-top: 60px;
      padding-top: 30px;
      border-top: 1px solid var(--border-color);
      color: var(--text-secondary);
      font-size: 0.9em;
    }

    .timestamp {
      margin-top: 5px;
      font-size: 0.85em;
    }

    .loading {
      text-align: center;
      padding: 20px;
      color: var(--text-secondary);
    }

    @media (max-width: 768px) {
      .container {
        padding: 20px 15px;
      }

      .title {
        font-size: 1.8em;
      }

      .exchange {
        padding: 15px;
      }

      .metadata {
        flex-direction: column;
        gap: 15px;
      }
    }
  `;
}

/**
 * Generate metadata HTML
 */
function generateMetadataHTML(conversation) {
  return `
    <div class="metadata">
      <div class="metadata-item">
        <span class="metadata-label">Platform</span>
        <span class="metadata-value">${escapeHTML(conversation.platform)}</span>
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Exchanges</span>
        <span class="metadata-value">${conversation.exchanges.length}</span>
      </div>
      <div class="metadata-item">
        <span class="metadata-label">Created</span>
        <span class="metadata-value">${new Date(conversation.created).toLocaleDateString()}</span>
      </div>
    </div>
  `;
}

/**
 * Generate exchanges HTML
 */
function generateExchangesHTML(conversation, showControls) {
  return conversation.exchanges.map((exchange, index) => {
    const participant = conversation.participants.find(p => p.id === exchange.participantId);
    const name = participant ? participant.name : 'Unknown';
    const role = exchange.role;

    return `
      <div class="exchange ${role}" data-exchange-id="${index}">
        <div class="exchange-header">
          <div class="speaker">
            <span class="speaker-name">${escapeHTML(name)}</span>
            <span class="speaker-badge">${role}</span>
          </div>
          ${showControls ? `
          <div class="exchange-controls">
            <button class="play-btn" data-index="${index}">
              <span class="play-icon">▶</span>
              <span class="play-text">Play</span>
            </button>
          </div>
          ` : ''}
        </div>
        <div class="text">${escapeHTML(exchange.text)}</div>
      </div>
    `;
  }).join('\n');
}

/**
 * Generate control panel HTML
 */
function generateControlPanelHTML() {
  return `
    <div class="control-panel">
      <div class="control-panel-header">Playback Controls</div>
      <div class="control-buttons">
        <button class="control-btn" id="play-all-btn">▶ Play All</button>
        <button class="control-btn" id="stop-btn">⏹ Stop</button>
        <button class="control-btn" id="prev-btn">⏮ Previous</button>
        <button class="control-btn" id="next-btn">⏭ Next</button>
      </div>
    </div>
  `;
}

/**
 * Generate JavaScript for audio playback
 */
function generateJavaScript(conversation, autoPlay) {
  const conversationJSON = JSON.stringify(conversation).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

  return `
    // Conversation data
    const conversation = JSON.parse('${conversationJSON}');
    let currentIndex = -1;
    let isPlaying = false;
    let currentUtterance = null;

    // Initialize speech synthesis
    const synth = window.speechSynthesis;

    // Get voice for participant
    function getVoice(participantId) {
      const participant = conversation.participants.find(p => p.id === participantId);
      if (!participant || !participant.voiceProfile) {
        return null;
      }

      const voices = synth.getVoices();
      const voiceName = participant.voiceProfile.voice || participant.voiceProfile.webSpeech?.voice;

      if (voiceName) {
        return voices.find(v => v.name.includes(voiceName)) || voices[0];
      }

      return voices[0];
    }

    // Play single exchange
    function playExchange(index) {
      if (index < 0 || index >= conversation.exchanges.length) return;

      stopPlayback();
      currentIndex = index;

      const exchange = conversation.exchanges[index];
      const participant = conversation.participants.find(p => p.id === exchange.participantId);

      // Don't play user messages (only LLM responses)
      if (exchange.role === 'user') {
        console.log('[Audio] Skipping user message');
        highlightExchange(index);
        return;
      }

      const utterance = new SpeechSynthesisUtterance(exchange.text);

      // Apply voice profile
      if (participant && participant.voiceProfile) {
        const vp = participant.voiceProfile.webSpeech || participant.voiceProfile;
        utterance.rate = vp.rate || vp.speed || 1.0;
        utterance.pitch = vp.pitch || 1.0;
        utterance.volume = vp.volume || 1.0;
        utterance.voice = getVoice(exchange.participantId);
      }

      utterance.onstart = () => {
        isPlaying = true;
        highlightExchange(index);
        updatePlayButton(index, true);
      };

      utterance.onend = () => {
        isPlaying = false;
        unhighlightExchange(index);
        updatePlayButton(index, false);
        currentUtterance = null;
      };

      currentUtterance = utterance;
      synth.speak(utterance);
    }

    // Stop playback
    function stopPlayback() {
      if (isPlaying) {
        synth.cancel();
        if (currentIndex >= 0) {
          unhighlightExchange(currentIndex);
          updatePlayButton(currentIndex, false);
        }
        isPlaying = false;
        currentUtterance = null;
      }
    }

    // Play all exchanges sequentially
    function playAll() {
      let index = 0;

      function playNext() {
        if (index >= conversation.exchanges.length) {
          stopPlayback();
          return;
        }

        const exchange = conversation.exchanges[index];

        if (exchange.role === 'user') {
          // Skip user messages
          index++;
          setTimeout(playNext, 500);
        } else {
          playExchange(index);

          if (currentUtterance) {
            currentUtterance.onend = () => {
              isPlaying = false;
              unhighlightExchange(index);
              updatePlayButton(index, false);
              index++;
              setTimeout(playNext, 1000);
            };
          } else {
            index++;
            setTimeout(playNext, 500);
          }
        }
      }

      playNext();
    }

    // Highlight exchange
    function highlightExchange(index) {
      const exchange = document.querySelector(\`[data-exchange-id="\${index}"]\`);
      if (exchange) {
        exchange.classList.add('playing');
        exchange.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }

    // Unhighlight exchange
    function unhighlightExchange(index) {
      const exchange = document.querySelector(\`[data-exchange-id="\${index}"]\`);
      if (exchange) {
        exchange.classList.remove('playing');
      }
    }

    // Update play button
    function updatePlayButton(index, playing) {
      const btn = document.querySelector(\`[data-index="\${index}"]\`);
      if (btn) {
        const icon = btn.querySelector('.play-icon');
        const text = btn.querySelector('.play-text');
        if (playing) {
          icon.textContent = '⏸';
          text.textContent = 'Pause';
        } else {
          icon.textContent = '▶';
          text.textContent = 'Play';
        }
      }
    }

    // Event listeners
    document.querySelectorAll('.play-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        const index = parseInt(btn.dataset.index);
        if (currentIndex === index && isPlaying) {
          stopPlayback();
        } else {
          playExchange(index);
        }
      });
    });

    const playAllBtn = document.getElementById('play-all-btn');
    if (playAllBtn) {
      playAllBtn.addEventListener('click', playAll);
    }

    const stopBtn = document.getElementById('stop-btn');
    if (stopBtn) {
      stopBtn.addEventListener('click', stopPlayback);
    }

    const prevBtn = document.getElementById('prev-btn');
    if (prevBtn) {
      prevBtn.addEventListener('click', () => {
        if (currentIndex > 0) {
          playExchange(currentIndex - 1);
        }
      });
    }

    const nextBtn = document.getElementById('next-btn');
    if (nextBtn) {
      nextBtn.addEventListener('click', () => {
        if (currentIndex < conversation.exchanges.length - 1) {
          playExchange(currentIndex + 1);
        }
      });
    }

    // Load voices
    synth.addEventListener('voiceschanged', () => {
      console.log('[Audio] Voices loaded:', synth.getVoices().length);
    });

    ${autoPlay ? 'window.addEventListener("load", () => playAll());' : ''}
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHTML(str) {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

/**
 * Download HTML file
 */
function downloadHTML(html, filename = 'conversation.html') {
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Export for use in extension
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    exportToHTML,
    downloadHTML
  };
}
  `;
}

// Make functions available globally
if (typeof window !== 'undefined') {
  window.exportToHTML = exportToHTML;
  window.downloadHTML = downloadHTML;
}
